replicaCount: 3

spring:
  profile: dev

image:
  repository: busybox
  tag: stable
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  ports:
    - name: api
      port: 8080
      targetPort: 8080
    - name: logs
      port: 8081
      targetPort: 8081
    - name: soap
      port: 8082
      targetPort: 8082

ingress:
  enabled: true
  annotations: {}
  subdomain: dev
  domain: example.com
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

configMap:
  config.json: |
    {
      "key": "value"
    }
