replicaCount: 3

image:
  repository: busybox
  tag: stable
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  ports:
    - name: api
      port: 8080
      targetPort: 8080
    - name: logs
      port: 8081
      targetPort: 8081
    - name: soap
      port: 8082
      targetPort: 8082

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: spring-boot-api.local
      paths:
        - path: /api
          pathType: Prefix
          port: 8080
        - path: /logs
          pathType: Prefix
          port: 8081
        - path: /soap
          pathType: Prefix
          port: 8082
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

configMap:
  config.json: |
    {
      "key": "value"
    }
