apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "spring-boot-api.fullname" . }}-ingress
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  rules:
  - host: {{ .Values.ingress.subdomain }}.{{.Values.ingress.domain}}
    http:
      paths:
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: {{ include "spring-boot-api.fullname" . }}-service
              port:
                number: 8080
        - path: /logs
          pathType: Prefix
          backend:
            service:
              name: {{ include "spring-boot-api.fullname" . }}-service
              port:
                number: 8081
        - path: /soap
          pathType: Prefix
          backend:
            service:
              name: {{ include "spring-boot-api.fullname" . }}-service
              port:
                number: 8082
