apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spring-boot-api.fullname" . }}-secret
type: Opaque
data:
  key1: {{ randAlphaNum 64 | b64enc | quote }}
  key2: {{ randAlphaNum 64 | b64enc | quote }}
