apiVersion: v1
kind: Service
metadata:
  name: {{ include "spring-boot-api.fullname" . }}-service
spec:
  selector:
    app: {{ include "spring-boot-api.name" . }}
  ports:
  {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
  {{- end }}
  type: {{ .Values.service.type }}
